# See https://raw.githubusercontent.com/golangci/golangci-lint/master/.golangci.example.yml

run:
  timeout: 5m

  skip-files:
    - ".*_mock\\.go$"
    - "\\.pb\\.go$"

output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  format: colored-line-number

linters:
  enable:
    - depguard
    - dupl
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gosec
    - govet
    - lll
    - megacheck
    - misspell
    - nakedret
    - prealloc
    - revive
    - stylecheck
    - unconvert
    - unparam

linters-settings:
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com/Shopify/goose
  golint:
    min-confidence: 0
  lll:
    line-length: 140
  maligned:
    suggest-new: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - bodyclose
        - dupl
        - errcheck
        - gocyclo
        - gosec
        - lll
        - scopelint

    - path: /doc\.go$
      linters:
        - lll

    - linters:
        - lll
      source: "^//go:generate "
