# See https://raw.githubusercontent.com/golangci/golangci-lint/master/.golangci.example.yml

run:
  timeout: 5m

output:
  formats:
    - format: colored-line-number
      path: stdout

linters:
  enable:
    - dupl
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gosec
    - govet
    - lll
    - misspell
    - nakedret
    - prealloc
    - stylecheck
    - unconvert
    - unparam
    - gosimple
    - staticcheck
    - unused

linters-settings:
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3 # now is inclusive
  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com/Shopify/goose
  golint:
    min-confidence: 0
  lll:
    line-length: 140
  maligned:
    suggest-new: true
  gosec:
    excludes:
      - G115
issues:
  exclude-files:
    - ".*_mock\\.go$"
    - "\\.pb\\.go$"

  exclude-rules:
    - path: _test\.go
      linters:
        - bodyclose
        - dupl
        - errcheck
        - gocyclo
        - gosec
        - lll
        - scopelint

    - path: /doc\.go$
      linters:
        - lll

    - linters:
        - lll
      source: "^//go:generate "