name: goose

up:
  - homebrew:
      - golangci/tap/golangci-lint:
          version: v1.22.2
  - go:
      version: "1.13.7"
      modules: true

commands:
  doc-server: |
    echo "Hosting documentation server at http://localhost:6060/github.com/Shopify/goose"
    godoc -http=:6060
  test: go test -race ./...
  style:
    run: golangci-lint run
    desc: Static verification using golangci-lint.
    syntax:
      optional: --fix
