name: goose

up:
  - go:
      version: "1.21.4"
      modules: true

commands:
  doc-server: |
    echo "Hosting documentation server at http://localhost:6060/github.com/Shopify/goose"
    godoc -http=:6060
  test: go test -race ./...
  style:
    run: bin/style
    desc: Static verification using gometalinter or autofix issues when possible.
    syntax:
      optional: --fix
