name: CI

on:
  push:
    tags:
    - v*
    branches:
    - master
    - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3.3.1
      with:
        version: v1.49.0

  mod-tidy:
    name: Go Mod Tidy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0

    - name: Setup go
      uses: actions/setup-go@v3.3.0
      with:
        go-version: 1.15.x

    - name: Cache
      uses: actions/cache@v3.0.10
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Tidy
      run: |
        cp go.sum{,.old}
        go mod tidy
        diff go.sum{.old,}

  test:
    name: Go ${{ matrix.go-version }} test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version:
        - 1.17.x
        - 1.18.x
        - 1.19.x

    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0

    - name: Setup go
      uses: actions/setup-go@v3.3.0
      with:
        go-version: ${{ matrix.go-version }}

    - name: Cache
      uses: actions/cache@v3.0.10
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Test
      run: go test -v -race ./...
