// Code generated by mockery v1.0.0. DO NOT EDIT.

package metrics

import (
	context "context"
)
import mock "github.com/stretchr/testify/mock"

import time "time"

// MockBackend is an autogenerated mock type for the MockBackend type
type MockBackend struct {
	mock.Mock
}

// Count provides a mock function with given fields: ctx, name, value, tags, rate
func (_m *MockBackend) Count(ctx context.Context, name string, value int64, tags Tags, rate float64) error {
	ret := _m.Called(ctx, name, value, tags, rate)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, Tags, float64) error); ok {
		r0 = rf(ctx, name, value, tags, rate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Distribution provides a mock function with given fields: ctx, name, value, tags, rate
func (_m *MockBackend) Distribution(ctx context.Context, name string, value float64, tags Tags, rate float64) error {
	ret := _m.Called(ctx, name, value, tags, rate)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, float64, Tags, float64) error); ok {
		r0 = rf(ctx, name, value, tags, rate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Gauge provides a mock function with given fields: ctx, name, value, tags, rate
func (_m *MockBackend) Gauge(ctx context.Context, name string, value float64, tags Tags, rate float64) error {
	ret := _m.Called(ctx, name, value, tags, rate)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, float64, Tags, float64) error); ok {
		r0 = rf(ctx, name, value, tags, rate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Histogram provides a mock function with given fields: ctx, name, value, tags, rate
func (_m *MockBackend) Histogram(ctx context.Context, name string, value float64, tags Tags, rate float64) error {
	ret := _m.Called(ctx, name, value, tags, rate)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, float64, Tags, float64) error); ok {
		r0 = rf(ctx, name, value, tags, rate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Set provides a mock function with given fields: ctx, name, value, tags, rate
func (_m *MockBackend) Set(ctx context.Context, name string, value string, tags Tags, rate float64) error {
	ret := _m.Called(ctx, name, value, tags, rate)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, Tags, float64) error); ok {
		r0 = rf(ctx, name, value, tags, rate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Timing provides a mock function with given fields: ctx, name, value, tags, rate
func (_m *MockBackend) Timing(ctx context.Context, name string, value time.Duration, tags Tags, rate float64) error {
	ret := _m.Called(ctx, name, value, tags, rate)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration, Tags, float64) error); ok {
		r0 = rf(ctx, name, value, tags, rate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
